server:
  port: 9999

tengxunyun:
  im:
    sdkAppId: 1400488038
    adminName: administrator
    priKey: 59156f9b8d6af2dc897299880c03b75bedad34d95eb8e74aa1adb297d96a61f5
    baseUri: https://console.tim.qq.com/v4/
    userSigExpiration: 604800